spring:
  application:
    name: shop-service

  config:
    import: optional:configserver:http://config-server:8888

server:
  port: 0

openapi:
  service:
    url: https://localhost:8000/shop-service