spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:http://config-server:8080

server:
  port: 0

openapi:
  service:
    url: https://localhost:8000/auth-service