spring:
  application:
    name: payment-service

  config:
    import: optional:configserver:http://config-server:8888

server:
  port: 0

openapi:
  service:
    url: https://localhost:8000/payment-service