spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://config-server:8080

server:
  port: 8080

openapi:
  service:
    url: https://localhost:8000/user-service