spring:
  application:
    name: delivery-service

  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 0

openapi:
  service:
    url: https://localhost:8000/delivery-service